* Introduction

  # In this section make an introduction to your report and give brief information about where you have done your training (more info about that will be given in the next section) and your motivation for choosing this place. Briefly summarize the work you have done, the motivation behind your work, and the significance of the work you have done in the overall project.
  # Please remove these explanations in this template after you read them or while you are writing your report. These explanations are marked with yellow color like here. Make sure you read and correct your report a few times after you write it.
  # Please modify the parts that are marked with green color in this template according to your case (for example in the Cover Page).
  # You need to be careful about putting references to the end of the report and citing them properly in the text like the example just here [2,4,5,10]. You can cite a single reference like this [3].
  # Please make sure you follow a good writing style while writing your report. There are a lot of resources in Internet and Library about academic/report writing in English language. Information about some writing resources that you can benefit are added to the reference list at the end [1,2,3,4,12,13].
  # Please also explain the organization of the rest of the report in the last paragraph of this section.

* Company Information

** About the company
   The internship is completed in the company BK Mobil[1]. BK Mobil is a software company focused on
   education technologies. It's main office is located in Bilkent Cyberpark. It also has two other
   offices in Istanbul.

   The main product of BK Mobil is called Metodbox[2]. It is an online learning platform that is
   used by primary and high school students. It is available as a website and mobile applications
   for Android and IOS operating systems. It consists of many features like lectures, lecture
   videos, exam reports, performance metrics for students. Also, it is used integrated with
   teachers, administrative staff and parents. Teachers and administrative staff use Metodbox for
   assigning homework, communicating with students using instant messaging feature, and tracking
   individual or success of students. Lastly, parents can use Metodbox to keep updated about the
   progress of their children. Metodbox also uses AI concepts to implement some advanced features
   like grading automation, information review adaptive learning and personalized learning.

   Other than Metodbox, BK Mobil also has a video conferencing solution SeeMeet[3], a project based
   learning platform Metodbox Bee[4] and specific applications implemented for Uğur Schools and
   Bahçeşehir College.

** About your department

** About the hardware and software systems

   The company was flexible in terms of hardware and software. Although they offered to give me a
   laptop, I had the option to use my own computer. Therefore, I used my own laptop instead of
   theirs. However, the laptops of the company are mostly Dell computers with Windows operating
   system. However, there were people using Mac and Linux computers as well.

   The company uses Bitbucket[5] for source code hosting. For the project I worked on, ReactJS[6] is
   used for front-end and PHP is used for back-end.

** About your supervisor

   During my internship, my supervisor was Ahmet İlhan Aydoğdu. He is graduated from Pamukkale
   University, Department of Computer Engineering in 2017. He works as a software developer in
   BK mobil for four years. He also has similar experience in two other companies as a Software
   Engineer.
   # The supervisor’s name and job title, along with his or her university and department and year of graduation must be stated here.

* Work Done
  # This section can have one or more subsections. It is up to you. But this section should be detailed enough.

** Learning React

   In the first day of my internship, my supervisor asked me which technologies I have experience
   with. Since my company is a mobile and web company, I told them my mobile application experience
   which I acquired during my CS102 project and my Senior project using Java. He asked more
   specifically about my web experience with JavaScript and ReactJS. Since I had no experience with
   them, my supervisor asked me to learn them at first by following tutorials and implement a basic
   project with the tutorials.

   I started learning React with a YouTube tutorial[7]. While watching the tutorial, I tried to do
   the coding on my own as well. The tutorial was on implementing a todo list with adding todo,
   marking todos as completed or not completed and clearing completed todos. I implemented the list
   according to the tutorial. After completing the tutorial, I wanted to add some extra features
   that were not present in the original tutorial. Therefore, I added filtering feature, where user can
   filter todos as all todos, only completed todos or only active todos. Lastly, I added a Dark mode
   feature where user can choose to use dark mode instead of white mode. I  pushed the resulting
   project in a public GitHub repository[8].

*** Learning Service Usage
    After learning React generally, my supervisor asked me to implement a project that uses an API
    and using services. Specifically, he asked me to implement a project from a YouTube
    tutorial[9]. The aim is to implement a website that displays different tours by fetching data
    from an API. User can click on "Not interested" button for each tour to hide it. When the page
    is refreshed, all content is fetched again. After understanding what it does, I implemented the
    project on my own, without following the tutorial. I focused on technical side like using
    services rather than aesthetics. I pushed the resulting project in a public GitHub
    repository[10].

*** Learning React Routers
    After completing my first project and checking with my supervisor, my supervisor asked me to
    learn two more concepts, which are Routers and Redux and show them in projects. Therefore, I
    started with learning Routers.

    In order to learn what Routers are and how they are used in React, I used a documentation about
    it[11]. Routers are React components that are used for easy navigation among different pages. In
    order to test my knowledge, I implemented a simple template web page that have a home page, an
    about page and a contact page, where users can switch among pages using the navigation bar on top
    of each page and navigation is done with React Routers.

    In this simple project, communication cost between client and server is reduced. In a classic
    web page, every time user switches among two pages, a new request is sent to the server and new
    web page content is sent back by the server. However, using React and Routers, this is reduced
    to a single request. At the first connection, user takes the contents of pages and loading
    another page is done on the client-side. I pushed the resulting project in a public GitHub
    repository again[12].

*** Learning React Redux
    Later, I started learning about Redux and its usage with React. In order to do this, I followed
    a YouTube tutorial again[13]. In React, data can be passed among React components in a single
    direction, among parent and child. However, it cannot be passed among siblings. In order to two
    Component to use the same data, the data must be stored at least in their lowest common
    ancestor. Therefore, data is tend to be stored somewhere else than the places it is used. This
    creates a lack of organization. This problems can be solved with Redux. With Redux, data is
    stored in a distinct place where it is accessible from components by methods provided by the
    library.

    In order to see a working example of Redux, I implemented a simple counter following a
    tutorial[13]. There is a counter with initial value zero and there are two buttons to
    increment and decrement the counter value by one. Although it is not very convenient to use
    Redux in this project, it was useful to learn because it takes time to set up Redux and it is
    easier to not to use in small projects. However, it was helpful to learn how the concept
    works. The resulting project is pushed in a public GitHub repository[14].

** Mentonet
   After completing all tasks and checking them with my supervisor, I am granted access to a real
   project which is called Mentonet[15]. This project is a website for sharing surveys with
   students. It is still not deployed and under development. It is being developed using ReactJS on
   front-end and PHP on back-end. Its source code is stored in Bitbucket.

*** Setup and Adaptation
    In order to start the project, I created a Bitbucket account and company invited me to the
    repository. I cloned the repository and made necessary configurations in order to run it
    locally. Later I examined the website by simply using it without checking the code. Later, I
    started from main component and tried to understand its working by tracing the code. I made
    minor changes in the code when necessary, in order to understand what each component do. This
    way I familiarized myself with the code and its organization. This way I could know where to
    look when I need something.

*** Settings Page
    After getting used to the project, my supervisor asked me to implement the settings page of
    Mentonet. Using this page, an administrator can set the settings like the deadline and the goal
    of the survey. Similarly, it is possible to set which degrees are going to solve the survey
    using this screen as well. A screenshot of this screen is included in Appendix 1.

*** Formatting Surveys List
    After completing the Settings page, my supervisor asked me to format the survey list page. In
    this page, a user can see the list of surveys he/she is authorized to see. Administrators can
    click the button next to each survey in the list to edit the survey or guests can click a
    similar button next to each list item in order to solve that survey. This page was already
    implemented, however I formatted this page so that more information is displayed, and full
    description of the survey is displayed on a popover when hovered on a list item. Necessary
    changes are done on the routers in order to display different buttons for administrators and
    guests. A screenshot of this screen is included in Appendix 2.

*** Solve Survey Page
    When I completed all work with the surveys list, I am asked to implement survey solving
    page. This page is designed for guests to solve the surveys. In this page, each question of
    different possible types is displayed sequentially. User can mark or type his/her answers and
    can submit the form by clicking on a button. Implementation of this page is done using the
    implementation of survey creation page. Since survey creation page is similar to survey solving
    page, it was possible to make some changes on the code to implement the new code, instead of
    starting from scratch. A screenshot of this page is included in Appendix 3.

* Performance and Outcomes
  # You must have all these sections in your report.

** Solving Complex Engineering Problems

** Recognizing Ethical and Professional Responsibilities

   During my internship, I faced some ethical and professional responsibilities. I understood these
   responsibilities and followed them during my internship.

*** Ethical Responsibilities

    While implementing the tasks that are assigned to me, ethical responsibilities are followed. For
    example, while implementing Mentonet, although there are easier ways to do something, the most
    efficient way is searched. This way unnecessary resource usage is prevented. This way the users
    can reach the content provided with small amount of data, battery, CPU usage etc. This is an
    ethical responsibility of the developer against both the users and the nature. For example,
    instead of sending request for each page each time, less requests are used and navigation among
    pages is done on client side. This way the communication cost is reduced.

*** Professional Responsibilities


** Making Informed Judgments

** Acquiring New Knowledge by Using Appropriate Learning Strategies

   The tools that are used during my internship mostly were not familiar to me. Before my
   internship, I had no experience with web development and ReactJS. Therefore, I was not qualified
   enough to contribute to a real project. Therefore I am asked to learn React by my
   supervisor. Also, I learned sub-concepts of React by implementing small projects. In order to do
   this, I used YouTube videos. However, instead of simply watching a video, I made the
   implementation and even took them further. This was the main strategy I used for learning.

** Applying New Knowledge As Needed

   The knowledge learned and explained in the previous section are used during the tasks assigned to
   me. Programming with React, which was a new skill for me was used in a real-life project called
   Mentonet. Sub-concepts like Redux and Routers are also very useful in Mentonet. The transitions
   between pages are implemented in an organized and readable way using React routers. Similarly,
   the communication between front-end and back-end are handled using Redux with a similar organized
   and readable approach.

* Conclusions
  # Here you will write your conclusions. You can discuss your training and the company as well. Give a summary of the most important things you learned.

* References

  + [1]"BK Mobil | BK Tomorrow - future of education technology",
    Bktomorrow.com. [Online]. Available: https://bktomorrow.com/. [Accessed: 15- Aug- 2022].
  + [2]"Metodbox | BK Mobil", Bktomorrow.com. [Online]. Available:
    https://bktomorrow.com/Metodbox2.html. [Accessed: 15- Aug- 2022].
  + [3]"SeeMeet | BK Mobil", Bktomorrow.com. [Online]. Available:
    https://bktomorrow.com/SeeMeet2.html. [Accessed: 15- Aug- 2022].
  + [4]"Metodbox Bee | BK Mobil", Bktomorrow.com. [Online]. Available:
    https://bktomorrow.com/Metodbox-Bee2.html. [Accessed: 15- Aug- 2022].
  + [5]"Bitbucket | Git solution for teams using Jira", Bitbucket. [Online]. Available:
    https://bitbucket.org. [Accessed: 15- Aug- 2022].
  + [6]"React – A JavaScript library for building user interfaces",
    Reactjs.org. [Online]. Available: https://reactjs.org/. [Accessed: 15- Aug- 2022].
  + [7]Web Dev Simplified, "Learn React In 30 Minutes", Youtube.com. [Online]. Available:
    https://www.youtube.com/watch?v=hQAHSlTtcmY. [Accessed: 15- Aug- 2022].
  + [8]B. Akyürek, "GitHub - berdanakyurek/React-Test", GitHub. [Online]. Available:
    https://github.com/berdanakyurek/React-Test. [Accessed: 15- Aug- 2022].
  + [9]"Code 15 React Projects - Complete Course", Youtube. [Online]. Available:
    https://youtu.be/a_7Z7C_JCyo?t=1181. [Accessed: 15- Aug- 2022].
  + [10]B. Akyürek, "GitHub - berdanakyurek/React-Tour-App", GitHub. [Online]. Available:
    https://github.com/berdanakyurek/React-Tour-App. [Accessed: 15- Aug- 2022].
  + [11]"React Router: Declarative Routing for React", ReactRouterWebsite. [Online]. Available:
    https://v5.reactrouter.com/web/guides/quick-start. [Accessed: 15- Aug- 2022].
  + [12]B. Akyürek, "GitHub - berdanakyurek/React-Router-Example", GitHub. [Online]. Available:
    https://github.com/berdanakyurek/React-Router-Example. [Accessed: 15- Aug- 2022].
  + [13]D. Ed, "Redux For Beginners | React Redux Tutorial", Youtube. [Online]. Available:
    https://youtu.be/CVpUuw9XSjY. [Accessed: 15- Aug- 2022].
  + [14]B. Akyürek, "GitHub - berdanakyurek/React-Redux-Example", GitHub, 2022. [Online]. Available:
    https://github.com/berdanakyurek/React-Redux-Example. [Accessed: 15- Aug- 2022].
  + [15]"Mentonet", Mentonet. [Online]. Available: https://dev.mentonet.com/. [Accessed: 15- Aug-
    2022].

* Appendices
